<?php
$page_title = "System Notifications";
require_once '../config/functions.php';
require_once '../db_connect.php';

check_login();
check_access('admin');

$message = '';

// --- I. Handle Mark As Read/Clear All Action ---
if (isset($_GET['action'])) {
    if ($_GET['action'] === 'read' && is_numeric($_GET['id'])) {
        $notif_id = (int)$_GET['id'];
        $sql = "UPDATE notifications SET is_read = TRUE WHERE notification_id = ?";
        $stmt = $conn->prepare($sql);
        $stmt->bind_param("i", $notif_id);
        if ($stmt->execute()) {
            $message = '<p class="success-message">Notification marked as read.</p>';
        }
        $stmt->close();
    } elseif ($_GET['action'] === 'clear_all') {
        $sql = "UPDATE notifications SET is_read = TRUE WHERE user_id IS NULL"; // Clear system notifications
        if ($conn->query($sql)) {
            $message = '<p class="success-message">All system notifications cleared.</p>';
        }
    }
}

// --- II. Fetch All Notifications (Unread and Read) ---
$notifications = [];
$sql = "SELECT notification_id, message, type, is_read, created_at FROM notifications WHERE user_id IS NULL ORDER BY created_at DESC";
$result = $conn->query($sql);
if ($result) {
    $notifications = $result->fetch_all(MYSQLI_ASSOC);
}


include '../template/header.php';
echo $message;
?>

<h2>System Notification Center</h2>
<p>Alerts generated by the system (e.g., low stock, critical errors).</p>
<p>
    <a href="?action=clear_all" class="btn btn-danger" onclick="return confirm('Are you sure you want to clear ALL system notifications?');">Clear All System Notifications</a>
</p>

<?php if (empty($notifications)): ?>
    <p>No system notifications found.</p>
<?php else: ?>
    <table>
        <thead>
            <tr>
                <th>Type</th>
                <th>Time</th>
                <th>Message</th>
                <th>Status</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($notifications as $notif): ?>
            <tr style="<?php echo $notif['is_read'] ? 'color: #888;' : 'font-weight: bold; background-color: #fff9e6;'; ?>">
                <td><?php echo htmlspecialchars($notif['type']); ?></td>
                <td><?php echo date('Y-m-d H:i', strtotime($notif['created_at'])); ?></td>
                <td><?php echo htmlspecialchars($notif['message']); ?></td>
                <td><?php echo $notif['is_read'] ? 'Read' : 'Unread'; ?></td>
                <td>
                    <?php if (!$notif['is_read']): ?>
                        <a href="?action=read&id=<?php echo $notif['notification_id']; ?>" class="btn">Mark Read</a>
                    <?php endif; ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>

<?php 
$conn->close();
include '../template/footer.php';
?>